name: Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_allowed_ip: ${{ secrets.ALLOWED_IP }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Debug GitHub
        run: |
          echo "repository=${{ github.repository }}"
          echo "ref=${{ github.ref }}"
          echo "workflow=${{ github.workflow }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::035885606922:role/githuboidc
          role-session-name: GitHubActions

      - name: Terraform Format
        working-directory: terraform
        run: terraform fmt -recursive

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate
        
      - name: Get Current IP
        run: |
          echo "TF_VAR_allowed_ip=$(curl -s https://checkip.amazonaws.com)/32" >> $GITHUB_ENV
          
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -input=false -var-file="dev.tfvars"

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -input=false -var-file="dev.tfvars"
