name: Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
      
      - name: Debug GitHub
        run: |
          echo "repository=${{ github.repository }}"
          echo "ref=${{ github.ref }}"
          echo "workflow=${{ github.workflow }}"

      - name: Debug OIDC2  
        env:
            ACTIONS_STEP_DEBUG: true
        run: | 
          echo "repo=${GITHUB_REPOSITORY}"    
          echo "ref=${GITHUB_REF}"
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::035885606922:role/githuboidc
          role-session-name: GitHubActions

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/modules
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
